/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 52539ec050a837b3dc48af1b04689274)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	METRICS_BROADCASTER: DurableObjectNamespace<import("./src/index").MetricsBroadcaster>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "MetricsBroadcaster";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
