import { computed, ref } from 'vue'

import { STORAGE } from './constants'

export type Language = 'zh' | 'en'

const zh = {
  dashboard: '监控页', admin: '管理后台', logout: '退出', retry: '重试', save: '保存', cancel: '取消', delete: '删除', edit: '编辑', refresh: '刷新', copy: '复制', copied: '已复制', enabled: '启用', disabled: '关闭', unset: '未设置', online: '在线', offline: '离线', hidden: '已隐藏', all: '全部', status: '状态', actions: '操作', server: '服务器', servers: '服务器', currentSite: '当前站点', allSites: '全部站点', siteNumber: '站点 {number}', themeAuto: '跟随系统', themeDark: '深色主题', themeLight: '浅色主题', switchLanguage: '切换语言',
  serverSummary: '服务器摘要', averageCpu: '平均 CPU', onlineOffline: '{online} 台在线 · {offline} 台离线', allOnlineNodes: '所有在线节点', downloadRate: '下载速率', uploadRate: '上传速率', total: '总计', realtimeTotal: '实时合计',
  monitoringSite: '监控站点', adminSite: '管理站点', monitorLoadFailed: '监控数据加载失败', partialSitesFailed: '部分站点无法访问', searchDashboard: '搜索名称、地址、系统或标签', displayMode: '展示模式', cardView: '卡片视图', ringView: '环形视图', tableView: '表格视图', mapView: '地图视图', loadingMonitor: '正在加载监控数据', memory: '内存', disk: '磁盘', timeout: '超时', monthlyTraffic: '月流量', noExpiry: '无到期时间', clearFilters: '清除筛选', monitorUnavailable: '监控数据不可用', noMatchingNodes: '没有符合条件的节点', noNodes: '暂未添加监控节点', node: '节点', resourceUsage: '资源使用率', realtimeNetwork: '实时网络', billingExpiry: '费用 / 到期', latency: '延迟', dataTime: '数据时间', price: '费用', expiry: '到期', unlimited: '不限', download: '下载', upload: '上传', runtime: '运行', load: '负载', openServerDetail: '打开节点详情',
  backDashboard: '返回监控页', loadingServer: '正在加载节点数据', historyRange: '历史时间范围', nodeSummary: '节点摘要', nodeNotFound: '找不到节点', nodeMissing: '该节点不存在或已经删除', adminRequired: '需要管理员登录', longHistoryRequiresAdmin: '查看 1 小时以上的历史记录需要管理员权限。', goLogin: '前往登录', cpuUsage: 'CPU 使用率', memoryUsage: '内存使用率', diskUsage: '磁盘使用率', networkLatency: '网络延迟', gpuUsage: 'GPU 使用率', system: '系统', kernel: '内核', cores: '{count} 核', memoryDisk: '内存 / 磁盘', systemLoad: '系统负载', uptime: '运行时间', bootTime: '启动时间', lastReport: '最后上报', totalTraffic: '总流量', realtimeSpeed: '实时网速', currentMonthTraffic: '本月流量', monthlyTrafficLimit: '月流量限额', networkThroughput: '网络吞吐', downstream: '下行', upstream: '上行', processes: '进程数', process: '进程', connections: 'TCP / UDP 连接', fourNetworkLatency: '四网延迟', packetLoss: '丢包率', telecom: '电信', unicom: '联通', mobile: '移动', baidu: '百度', minutesAgo: '{count} 分钟前', hoursAgo: '{count} 小时前', now: '现在', historyLoadFailed: '历史数据加载失败', serverLoadFailed: '无法从监控 API 获取该节点', noData: '暂无数据', chartLegend: '图表图例', trendChart: '{title}趋势图',
  loginAdmin: '登录管理后台', loginDescription: '选择管理站点并输入管理员凭据', username: '用户名', password: '密码', enterPassword: '请输入密码', login: '登录', selectAdminSite: '请选择管理站点', enterUsername: '请输入用户名', completeVerification: '请先完成安全验证', verificationFailed: '安全验证失败，请重试', invalidCredentials: '用户名或密码错误', loginFailed: '登录请求失败', missingTurnstileKey: '当前站点未配置 Turnstile Site Key',
  serversTab: '服务器', settingsTab: '全局设置', databaseTab: '数据库', searchAdmin: '搜索名称、地址、分组、标签或备注', allStatuses: '全部状态', deleteSelectedConfirm: '确定删除选中的 {count} 台服务器？', deleteItems: '删除 {count} 项', addServer: '添加服务器', moveUp: '上移', moveDown: '下移', group: '分组', tags: '标签', note: '备注', doubleClickCopy: '双击复制', billing: '费用', agent: 'Agent', public: '公开', installCommand: '安装命令', latestAgent: '最新 Agent {version}', agentOutdated: '可升级到 {version}',
  displaySettings: '展示设置', siteTitle: '站点标题', defaultView: '默认视图', card: '卡片', ring: '环形', table: '表格', backgroundImage: '背景图片', customHead: '自定义 Head', customScript: '自定义脚本', showPrice: '显示价格', showExpiry: '显示到期时间', showTraffic: '显示流量信息', showUpdateTime: '显示更新时间', allowLongHistory: '允许长期历史', collectionProbe: '采集与探测', telecomProbe: '电信探测点', unicomProbe: '联通探测点', mobileProbe: '移动探测点', baiduProbe: '百度探测点', notificationSettings: '通知设置', offlineDelay: '离线通知延迟', expiryReminder: '到期提醒', expiryReminderHint: '在服务器到期前发送通知', minutes: '{count} 分钟', sendTestNotification: '发送测试通知', securitySettings: '安全设置', adminUsername: '管理员用户名', publicMonitor: '公开监控页', globalTurnstile: '全站 Turnstile', loginTurnstile: '登录 Turnstile', staticCsp: '静态资源 CSP 来源', apiCsp: 'API CSP 来源', newAdminPassword: '新管理员密码', confirmPassword: '确认密码', cloudflareQuota: 'Cloudflare 与配额', queryQuota: '查询 D1 与 Workers 配额', saved: '已保存', saveSettings: '保存设置',
  exportServers: '导出服务器', exportDescription: '生成包含全部服务器配置的 JSON 备份。', exportConfig: '导出配置', importServers: '导入服务器', importDescription: '从 JSON 备份恢复服务器，重复 ID 将被跳过。', selectBackup: '选择备份文件', upgradeDatabase: '升级数据库', upgradeDescription: '检查并应用当前版本需要的数据库结构。', confirmUpgrade: '确认执行数据库升级？', upgrade: '升级', clearHistory: '清理历史数据', clearHistoryDescription: '保留服务器配置，仅删除历史监控记录。', confirmClearHistory: '确定清理全部历史记录？', clear: '清理', quotaTitle: 'D1 与 Workers 配额',
  basicInfo: '基本信息', serverName: '服务器名称', regionCode: '区域代码', tagsPlaceholder: '输入后回车', notePlaceholder: '可选，后台双击可快速复制', hidePublic: '从公开页面隐藏', disableOfflineNotification: '禁用离线通知', billingTraffic: '费用与流量', currency: '币种', billingCycle: '计费周期', expiryDate: '到期时间', autoRenewal: '自动续费', autoRenewalHint: '到期后自动顺延计费周期', trafficLimit: '月流量额度', trafficCalculation: '流量计算', resetDay: '重置日', rxCorrection: '下行修正', txCorrection: '上行修正', agentProbe: 'Agent 与探测', collectInterval: '采集间隔', reportInterval: '上报间隔', autoUpdate: '自动更新', autoInstallAgent: '自动安装新 Agent', autoUpdateWarning: '自动更新会执行远程升级脚本，请先确认节点环境兼容。', trafficTotal: '上下行合计', uploadOnly: '仅上行', downloadOnly: '仅下行', trafficMax: '取较大值', disableCachedSampling: '关闭缓存采样', seconds: '{count} 秒', invalidPingNode: '请输入有效的域名、IP 或 host:port', waitingInstall: '等待安装',
  commandTitle: '安装命令', trafficReset: '流量重置', monthlyDay: '每月 {day} 日', editParameters: '编辑参数', copyCommand: '复制命令', deleteServer: '删除服务器', confirmDelete: '确认删除', deleteWarning: '删除 {name} 后，其历史数据也将不可访问。', targetSystem: '目标系统', uninstallFirst: '建议先执行卸载命令', copyUninstall: '复制卸载命令', linuxAuto: 'Linux（自动检测发行版）', macPlatform: 'macOS（Intel / Apple Silicon）', windows: 'Windows', mapLabel: '节点区域地图', mapStyleFailed: '地图样式加载失败', mapComponentFailed: '地图组件加载失败', mapDataFailed: '地图数据加载失败', mapLoadFailed: '地图加载失败', nodeCount: '{count} 台节点',
  checkingAccess: '正在检查访问权限', siteMissingTurnstileKey: '站点 {number} 未配置 Turnstile Site Key', turnstileScriptFailed: 'Turnstile 脚本加载失败', redoVerification: '请重新完成安全验证', verificationComponentFailed: '安全验证组件加载失败', verificationExpired: '安全验证已过期，请重试', accessCheckFailed: '访问权限检查失败',
  autoRenewalShort: '自动续费', passwordMismatch: '两次输入的密码不一致', settingsMissing: '后端未返回站点设置', adminLoadFailed: '管理数据加载失败', serverIdMissing: '后端未返回新服务器 ID', serverSaved: '{name} 已保存', serverSaveFailed: '服务器保存失败', serverDeleted: '{name} 已删除', deleteFailed: '删除失败', batchDeleted: '已删除 {count} 台服务器', batchDeleteFailed: '批量删除失败', sortSaveFailed: '排序保存失败', serverVisibilityChanged: '{name} 已{state}', shown: '显示', hiddenState: '隐藏', statusUpdateFailed: '状态更新失败', monitorRefreshed: '监控数据已刷新', refreshFailed: '刷新失败', noteCopied: '备注已复制', usernameRequired: '管理员用户名不能为空', jwtTooShort: 'JWT Secret 至少需要 32 个字符', turnstileFieldsRequired: '启用 Turnstile 时必须填写 Site Key 和 Secret', notificationTargetRequired: '启用通知时必须填写 Telegram Bot Token 或通知 Webhook', settingsSaved: '全局设置已保存', settingsSaveFailed: '设置保存失败', notificationSent: '测试通知已发送', notificationFailed: '测试通知发送失败', quotaReadToday: '今日 D1 读取行数', quotaWriteToday: '今日 D1 写入行数', quotaWorkersToday: '今日 Workers 请求', quotaRead24h: '最近 24 小时 D1 读取', quotaUnavailable: 'API 未返回限额', quotaFailed: '配额查询失败', exportedServers: '已导出 {count} 台服务器', exportFailed: '导出失败', invalidBackup: '备份文件必须是服务器数组', importedServers: '已处理 {count} 台服务器', importFailed: '导入失败', databaseUpgraded: '数据库升级完成', historyCleared: '历史监控记录已清理', databaseFailed: '数据库操作失败',
  workersUpdate: 'Workers 可升级到 V{version}', workersCurrent: 'Workers V{version}', poweredBy: 'Powered by EdgeProbe',
} as const

type MessageKey = keyof typeof zh

const en: Record<MessageKey, string> = {
  dashboard: 'Dashboard', admin: 'Admin', logout: 'Log out', retry: 'Retry', save: 'Save', cancel: 'Cancel', delete: 'Delete', edit: 'Edit', refresh: 'Refresh', copy: 'Copy', copied: 'Copied', enabled: 'Enabled', disabled: 'Disabled', unset: 'Not set', online: 'Online', offline: 'Offline', hidden: 'Hidden', all: 'All', status: 'Status', actions: 'Actions', server: 'Server', servers: 'Servers', currentSite: 'Current site', allSites: 'All sites', siteNumber: 'Site {number}', themeAuto: 'System theme', themeDark: 'Dark theme', themeLight: 'Light theme', switchLanguage: 'Switch language',
  serverSummary: 'Server summary', averageCpu: 'Average CPU', onlineOffline: '{online} online · {offline} offline', allOnlineNodes: 'Across online nodes', downloadRate: 'Download rate', uploadRate: 'Upload rate', total: 'Total', realtimeTotal: 'Live total',
  monitoringSite: 'Monitoring site', adminSite: 'Admin site', monitorLoadFailed: 'Failed to load monitoring data', partialSitesFailed: 'Some sites are unavailable', searchDashboard: 'Search name, address, OS, or tag', displayMode: 'Display mode', cardView: 'Card view', ringView: 'Ring view', tableView: 'Table view', mapView: 'Map view', loadingMonitor: 'Loading monitoring data', memory: 'Memory', disk: 'Disk', timeout: 'Timeout', monthlyTraffic: 'Monthly traffic', noExpiry: 'No expiry date', clearFilters: 'Clear filters', monitorUnavailable: 'Monitoring data unavailable', noMatchingNodes: 'No matching nodes', noNodes: 'No monitored nodes yet', node: 'Node', resourceUsage: 'Resource usage', realtimeNetwork: 'Live network', billingExpiry: 'Billing / expiry', latency: 'Latency', dataTime: 'Data time', price: 'Price', expiry: 'Expires', unlimited: 'Unlimited', download: 'Download', upload: 'Upload', runtime: 'Uptime', load: 'Load', openServerDetail: 'Open server details',
  backDashboard: 'Back to dashboard', loadingServer: 'Loading server data', historyRange: 'History range', nodeSummary: 'Node summary', nodeNotFound: 'Server not found', nodeMissing: 'This server does not exist or was deleted', adminRequired: 'Admin login required', longHistoryRequiresAdmin: 'History beyond one hour requires administrator access.', goLogin: 'Go to login', cpuUsage: 'CPU usage', memoryUsage: 'Memory usage', diskUsage: 'Disk usage', networkLatency: 'Network latency', gpuUsage: 'GPU usage', system: 'System', kernel: 'Kernel', cores: '{count} cores', memoryDisk: 'Memory / disk', systemLoad: 'System load', uptime: 'Uptime', bootTime: 'Boot time', lastReport: 'Last report', totalTraffic: 'Total traffic', realtimeSpeed: 'Live speed', currentMonthTraffic: 'This month', monthlyTrafficLimit: 'Monthly limit', networkThroughput: 'Network throughput', downstream: 'Download', upstream: 'Upload', processes: 'Processes', process: 'Process', connections: 'TCP / UDP connections', fourNetworkLatency: 'Network latency', packetLoss: 'Packet loss', telecom: 'Telecom', unicom: 'Unicom', mobile: 'Mobile', baidu: 'Baidu', minutesAgo: '{count} min ago', hoursAgo: '{count} hr ago', now: 'Now', historyLoadFailed: 'Failed to load history', serverLoadFailed: 'Failed to load this server from the monitoring API', noData: 'No data', chartLegend: 'Chart legend', trendChart: '{title} trend chart',
  loginAdmin: 'Admin login', loginDescription: 'Choose a site and enter administrator credentials', username: 'Username', password: 'Password', enterPassword: 'Enter password', login: 'Log in', selectAdminSite: 'Select an admin site', enterUsername: 'Enter username', completeVerification: 'Complete the security check first', verificationFailed: 'Security verification failed. Try again.', invalidCredentials: 'Incorrect username or password', loginFailed: 'Login request failed', missingTurnstileKey: 'This site has no Turnstile Site Key',
  serversTab: 'Servers', settingsTab: 'Global settings', databaseTab: 'Database', searchAdmin: 'Search name, address, group, tag, or note', allStatuses: 'All statuses', deleteSelectedConfirm: 'Delete the selected {count} servers?', deleteItems: 'Delete {count}', addServer: 'Add server', moveUp: 'Move up', moveDown: 'Move down', group: 'Group', tags: 'Tags', note: 'Note', doubleClickCopy: 'Double-click to copy', billing: 'Billing', agent: 'Agent', public: 'Public', installCommand: 'Install command', latestAgent: 'Latest Agent {version}', agentOutdated: 'Upgrade available: {version}',
  displaySettings: 'Display settings', siteTitle: 'Site title', defaultView: 'Default view', card: 'Cards', ring: 'Rings', table: 'Table', backgroundImage: 'Background image', customHead: 'Custom Head', customScript: 'Custom script', showPrice: 'Show price', showExpiry: 'Show expiry date', showTraffic: 'Show traffic', showUpdateTime: 'Show update time', allowLongHistory: 'Allow long history', collectionProbe: 'Collection and probes', telecomProbe: 'Telecom probe', unicomProbe: 'Unicom probe', mobileProbe: 'Mobile probe', baiduProbe: 'Baidu probe', notificationSettings: 'Notifications', offlineDelay: 'Offline notification delay', expiryReminder: 'Expiry reminder', expiryReminderHint: 'Notify before a server expires', minutes: '{count} minutes', sendTestNotification: 'Send test notification', securitySettings: 'Security', adminUsername: 'Admin username', publicMonitor: 'Public dashboard', globalTurnstile: 'Site-wide Turnstile', loginTurnstile: 'Login Turnstile', staticCsp: 'Static asset CSP sources', apiCsp: 'API CSP sources', newAdminPassword: 'New admin password', confirmPassword: 'Confirm password', cloudflareQuota: 'Cloudflare and quotas', queryQuota: 'Query D1 and Workers usage', saved: 'Saved', saveSettings: 'Save settings',
  exportServers: 'Export servers', exportDescription: 'Create a JSON backup of every server configuration.', exportConfig: 'Export configuration', importServers: 'Import servers', importDescription: 'Restore from a JSON backup. Duplicate IDs are skipped.', selectBackup: 'Choose backup file', upgradeDatabase: 'Upgrade database', upgradeDescription: 'Check and apply the database schema required by this version.', confirmUpgrade: 'Run the database upgrade?', upgrade: 'Upgrade', clearHistory: 'Clear history', clearHistoryDescription: 'Keep server configuration and delete monitoring history only.', confirmClearHistory: 'Clear all monitoring history?', clear: 'Clear', quotaTitle: 'D1 and Workers usage',
  basicInfo: 'Basic information', serverName: 'Server name', regionCode: 'Region code', tagsPlaceholder: 'Type and press Enter', notePlaceholder: 'Optional; double-click to copy in the admin table', hidePublic: 'Hide from public dashboard', disableOfflineNotification: 'Disable offline notifications', billingTraffic: 'Billing and traffic', currency: 'Currency', billingCycle: 'Billing cycle', expiryDate: 'Expiry date', autoRenewal: 'Auto renewal', autoRenewalHint: 'Advance the date by one billing cycle after expiry', trafficLimit: 'Monthly traffic limit', trafficCalculation: 'Traffic calculation', resetDay: 'Reset day', rxCorrection: 'Download correction', txCorrection: 'Upload correction', agentProbe: 'Agent and probes', collectInterval: 'Collection interval', reportInterval: 'Report interval', autoUpdate: 'Auto update', autoInstallAgent: 'Install new Agent versions automatically', autoUpdateWarning: 'Auto update executes a remote upgrade script. Confirm node compatibility first.', trafficTotal: 'Upload + download', uploadOnly: 'Upload only', downloadOnly: 'Download only', trafficMax: 'Larger direction', disableCachedSampling: 'Disable cached sampling', seconds: '{count} seconds', invalidPingNode: 'Enter a valid domain, IP, or host:port', waitingInstall: 'Waiting for install',
  commandTitle: 'Install command', trafficReset: 'Traffic reset', monthlyDay: 'Day {day} of each month', editParameters: 'Edit parameters', copyCommand: 'Copy command', deleteServer: 'Delete server', confirmDelete: 'Confirm delete', deleteWarning: 'Deleting {name} also makes its history unavailable.', targetSystem: 'Target system', uninstallFirst: 'Run the uninstall command first', copyUninstall: 'Copy uninstall command', linuxAuto: 'Linux (auto-detect distribution)', macPlatform: 'macOS (Intel / Apple Silicon)', windows: 'Windows', mapLabel: 'Server region map', mapStyleFailed: 'Failed to load map styles', mapComponentFailed: 'Failed to load map component', mapDataFailed: 'Failed to load map data', mapLoadFailed: 'Failed to load map', nodeCount: '{count} nodes',
  checkingAccess: 'Checking access', siteMissingTurnstileKey: 'Site {number} has no Turnstile Site Key', turnstileScriptFailed: 'Failed to load the Turnstile script', redoVerification: 'Complete the security check again', verificationComponentFailed: 'Failed to load the security verification component', verificationExpired: 'Security verification expired. Try again.', accessCheckFailed: 'Access check failed',
  autoRenewalShort: 'Auto renewal', passwordMismatch: 'The passwords do not match', settingsMissing: 'The backend did not return site settings', adminLoadFailed: 'Failed to load admin data', serverIdMissing: 'The backend did not return a server ID', serverSaved: '{name} saved', serverSaveFailed: 'Failed to save server', serverDeleted: '{name} deleted', deleteFailed: 'Delete failed', batchDeleted: 'Deleted {count} servers', batchDeleteFailed: 'Batch delete failed', sortSaveFailed: 'Failed to save order', serverVisibilityChanged: '{name} is now {state}', shown: 'visible', hiddenState: 'hidden', statusUpdateFailed: 'Failed to update status', monitorRefreshed: 'Monitoring data refreshed', refreshFailed: 'Refresh failed', noteCopied: 'Note copied', usernameRequired: 'Admin username is required', jwtTooShort: 'JWT Secret must be at least 32 characters', turnstileFieldsRequired: 'Site Key and Secret are required when Turnstile is enabled', notificationTargetRequired: 'A Telegram Bot Token or notification webhook is required when notifications are enabled', settingsSaved: 'Global settings saved', settingsSaveFailed: 'Failed to save settings', notificationSent: 'Test notification sent', notificationFailed: 'Failed to send test notification', quotaReadToday: 'D1 rows read today', quotaWriteToday: 'D1 rows written today', quotaWorkersToday: 'Workers requests today', quotaRead24h: 'D1 rows read in 24 hours', quotaUnavailable: 'Limit unavailable from API', quotaFailed: 'Failed to query usage', exportedServers: 'Exported {count} servers', exportFailed: 'Export failed', invalidBackup: 'The backup must be an array of servers', importedServers: 'Processed {count} servers', importFailed: 'Import failed', databaseUpgraded: 'Database upgrade complete', historyCleared: 'Monitoring history cleared', databaseFailed: 'Database operation failed',
  workersUpdate: 'Workers update available: V{version}', workersCurrent: 'Workers V{version}', poweredBy: 'Powered by EdgeProbe',
}

const storedLanguage = typeof localStorage === 'undefined' ? '' : localStorage.getItem(STORAGE.LANGUAGE_PREFERENCE)
export const currentLanguage = ref<Language>(storedLanguage === 'en' ? 'en' : 'zh')
export const isEnglish = computed(() => currentLanguage.value === 'en')

export function setLanguage(language: Language): void {
  currentLanguage.value = language
  localStorage.setItem(STORAGE.LANGUAGE_PREFERENCE, language)
  document.documentElement.lang = language === 'zh' ? 'zh-CN' : 'en'
}

export function toggleLanguage(): Language {
  const next = currentLanguage.value === 'zh' ? 'en' : 'zh'
  setLanguage(next)
  return next
}

export function t(key: MessageKey, params: Record<string, string | number> = {}): string {
  let value = (currentLanguage.value === 'en' ? en[key] : zh[key]) || zh[key]
  for (const [name, replacement] of Object.entries(params)) value = value.replaceAll(`{${name}}`, String(replacement))
  return value
}

export function initLanguage(): void {
  setLanguage(currentLanguage.value)
}
